### ISSUE TITLE
Menu Sounds > Default sounds doesn't point to the right folder (Win10)

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#33]
When selecting the option Default sounds, it doesn't load a list of the default sounds, but an empty one in Win10.
Seems to be pointing to the wrong location because it erases the previously loaded list.

**Comment by tmhglnd** [comment]
What happens if you delete `sample-library.json` from `/Documents/Mercury/Data`, and restart the Project? Does it create a new file in that folder with all the files loaded correctly? Also, does it correctly load files if you choose `add sounds`? What is the result shown under `show loaded sounds`

**Comment by GuillemGongora** [comment]
Manually choosing the folder works and writes the paths correctly in `sample-library.json`. What seems to be the problem is automatically finding the default directory where the samples are located.
This is where mine are as shown in the created `.json` file:
`"noise_a": "C:/Users/Guillem/Documents/Max 8/Projects/mercury-master/mercury_ide_0.9.9/media/samples//noise/noise_a.wav"`
Also noticed a double `//` in the path.
This is the actual Win10 path to the file in case it's useful:
`C:\Users\Guillem\Documents\Max 8\Projects\mercury-master\mercury_ide_0.9.9\media\samples\noise\noise_a.wav`

**Comment by tmhglnd** [comment]
Okay! Will have to look into that. At least once you loaded the files it should keep using the last loaded selection. And also if you pull a newer version later on you shouldn't have to reload the samples since it still used the `sample-library.json` from the `Documents/Mercury/Data`

**Comment by tmhglnd** [comment]
This should be fixed in the latest commit. If not, could you check what is printed to the console on startup under `"system-info" : { "app" : .... }`, this should have the path to the project folder of Mercury ? For example:
```js
"system-info", 	{
	"user" : "/Users/<username>",
	"app" : "/Users/<username>/Documents/Max 8/Projects/mercury/mercury_ide_0.9.9/code",
	"type" : "Darwin",
	"release" : "16.7.0",
	"platform" : "darwin"
}
```

**Comment by GuillemGongora** [comment]
Not fixed. Sound library still points out to the previous manually assigned folder, but Sounds > Default sounds still doesn't point to the default folder.
Here's information on my `system-info`:
```
node.script: [ "system-info", 	{
		"user" : "C:\\Users\\Guillem",
		"app" : "C:\\Users\\Guillem\\Documents\\Max 8\\Projects\\mercury-master\\mercury_ide_0.9.9\\code",
		"tmp" : "C:\\Users\\Guillem\\AppData\\Local\\Temp",
		"type" : "Windows_NT",
		"release" : "10.0.18362",
		"platform" : "win32",
		"ip" : "DESKTOP-QLNR585"
	}
```

**Comment by tmhglnd** [comment]
Should be working now in b116463d9819fbd81b909ade9e20462fde3127e0
