### ISSUE TITLE
midiClock is not sending clock to external devices

### ISSUE THREAD

**Issue by oscarvanleest** [tmhglnd/mercury#52]
External devices are not receiving Mercurys' midi clock. Might have something to do with most midi port names having spaces in them?

**Comment by tmhglnd** [comment]
Will have to investigate, did you try:

```
set midiclock "a portname with spaces"
```

**Comment by JaysonDirkz** [comment]
Hi Oscar, I had the same problem. Maybe this will help: #53

**Comment by tmhglnd** [comment]
This is fixed in 42ea79581187e18743a4ad94f02291349bf64219, and also with a few enhancements as suggested in #53 by @JaysonDirkz

**Comment by oscarvanleest** [comment]
Still doesn't seem to be working for me, a test to make sure the device works with another simple max patch using the midiout object works fine.

**Comment by tmhglnd** [comment]
Okay, then i'll have to investigate further. I'll get back to this soon

**Comment by tmhglnd** [comment]
I've done some deeper digging and now it should correctly parse the input string with spaces, for example:

`set midiClock "AU DLS Synth 1"`

Please give it a try when you have the time and let me know :).
